added new pvforecast adapter
ioBroker/ioBroker.repositories pull request #1706
Opened 2022-02-27 19:46 UTC by Patrick-Walther

2022-02-27 22:40 UTC, Apollon77 commented
Please Update the PR to only contain your changes ... it seems that your bracnch was outdated!!

2022-02-28 07:41 UTC, Patrick-Walther reviewed
add only my pvforecast information

2022-02-28 07:49 UTC, Apollon77 commented
RE-CHECK!

2022-02-28 10:37 UTC, Patrick-Walther commented
fix the issue

2022-02-28 13:44 UTC, ldittmar81 commented on sources-dist.json
> +    "type": "weather",
There is an error here. Please delete the last ,

2022-02-28 13:45 UTC, ldittmar81 requested changes
There is an error on sources-dist.json

2022-03-14 07:26 UTC, Apollon77 commented
Hi, here some review feedback:
* first of all as @ldittmar81 already stated ... no github.com links please ... adjust please in repo PR
* Typo in Readme: should be "## License" :-)
* Admin depenendency ned to be in "globalDependencies" usually https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/io-package.json#L275-L277
* https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/io-package.json#L387 should be role "json" too (same state below) whth common-type=string
* please remove https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/main.js#L199-L207 if not needed
* please use ` 'system.adapter.' + this.namespace` here https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/main.js#L501 for "from"
* please check the weather roles vs https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md#weather ... maybe better matches are possible
Thank you for checking and adjusting
*

2022-03-14 17:02 UTC, MeisterTR commented
@Apollon77 all fixed

2022-03-15 08:16 UTC, Apollon77 commented
I have adjusted the Repo PR

2022-03-15 08:21 UTC, Apollon77 commented
Verified, then npm release of this version please and we are ready to merge

2022-04-05 03:43 UTC, MeisterTR commented
@Apollon77  ready to merge?

2022-05-15 21:06 UTC, Apollon77 commented
Put 1.0.1 in it for stabe

2022-05-15 21:06 UTC, Apollon77 commented
Sorry for the delay, welcome in the repo

2022-05-15 21:06 UTC, merged