Added haus-bus.de adapter
ioBroker/ioBroker.repositories pull request #1894
Opened 2022-08-10 20:10 UTC by hausbus

This adapter provides ioBroker support for all haus-bus.de components. It was test for 2 years by many different customers.

2022-08-10 20:49 UTC, Apollon77 commented
Thank you @hausbus ,

please also just  the icon in this PR to link to the https://raw.githubusercontent.com domain like the other link. Thank you

2022-08-11 05:02 UTC, hausbus commented
Hi Ingo,
was muss ich da genau machen?

Danke!
Herm
________________________________
From: Ingo Fischer ***@***.***>
Sent: Wednesday, August 10, 2022 10:49:54 PM
To: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; Mention ***@***.***>
Subject: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894)


Thank you @hausbus<https://github.com/hausbus> ,

please also just the icon in this PR to link to the https://raw.githubusercontent.com domain like the other link. Thank you

—
Reply to this email directly, view it on GitHub<https://github.com/ioBroker/ioBroker.repositories/pull/1894#issuecomment-1211256127>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHEIMDVCYUYNJQDRXHY6IPTVYQIXFANCNFSM56FZXZXQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-11 10:23 UTC, Apollon77 commented
Diese Zeile hier https://github.com/ioBroker/ioBroker.repositories/pull/1894/files#diff-1384831e45cb5b5fc71b065c642c35169d0ee196221e07b4b81075a0d3b0aed8R674 korrigieren? :-)

2022-08-11 17:06 UTC, hausbus commented
fixed icon link

2022-09-06 10:17 UTC, GermanBluefox commented
RE-CHECK!

2022-09-06 10:17 UTC, GermanBluefox commented
RE-CHECK!

2022-09-06 10:18 UTC, GermanBluefox commented
## Automated adapter checker

### [ioBroker.hausbus_de](https://github.com/hausbus/ioBroker.hausbus_de)
[![Downloads](https://img.shields.io/npm/dm/iobroker.hausbus_de.svg)](https://www.npmjs.com/package/iobroker.hausbus_de) 
[![NPM](https://nodei.co/npm/iobroker.hausbus_de.png?downloads=true)](https://nodei.co/npm/iobroker.hausbus_de/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/hausbus/ioBroker.hausbus_de/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "hausbus_de" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

2022-09-06 10:18 UTC, GermanBluefox commented
## Automated adapter checker

### [ioBroker.hausbus_de](https://github.com/hausbus/ioBroker.hausbus_de)
[![Downloads](https://img.shields.io/npm/dm/iobroker.hausbus_de.svg)](https://www.npmjs.com/package/iobroker.hausbus_de) 
[![NPM](https://nodei.co/npm/iobroker.hausbus_de.png?downloads=true)](https://nodei.co/npm/iobroker.hausbus_de/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/hausbus/ioBroker.hausbus_de/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "hausbus_de" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

2022-09-16 09:59 UTC, Apollon77 commented
@hausbus Did you had a look at the comments of the automatic checker? Especially W156 and W505

2022-09-16 11:47 UTC, Apollon77 commented
Hello, thank for your submission, here some review comments:
* you use the release script, but did not updated to v3 correctly. There is another dependency for the iobroker plugin and a release config file needed. Please check release-script changelog for 3.0. It will not work as it is not because the io-package is not handled correctly.
* please add all config parameter in io-package in native are with their default values. If really no config variables are needed please remove the two dummy ones :-) (really not e.g. the network interface to use for devices with multiple or such?) 
* your config states that compact mode is supported, but code is not written for it. https://github.com/hausbus/ioBroker.hausbus_de/blob/main/io-package.json#L74 .Would be cool to see it supported ... 
* see https://github.com/hausbus/ioBroker.hausbus_de/commit/4c331b3930457a9b8d8dbb42d06c7349644d61e8#r84160575

Thank you for checking and adjusting to the comments

Ingo

2022-09-16 12:26 UTC, hausbus commented
Hey Ingo,
 thank you for your hints.
How comes that the release Skript ist not correct although I used the latest adapter creator?

Hermann
________________________________
From: Ingo Fischer ***@***.***>
Sent: Friday, September 16, 2022 1:47:17 PM
To: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; Mention ***@***.***>
Subject: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894)


Hello, thank for your submission, here some review comments:

  *   you use the release script, but did not updated to v3 correctly. There is another dependency for the iobroker plugin and a release config file needed. Please check release-script changelog for 3.0. It will not work as it is not because the io-package is not handled correctly.
  *   please add all config parameter in io-package in native are with their default values. If really no config variables are needed please remove the two dummy ones :-) (really not e.g. the network interface to use for devices with multiple or such?)
  *   your config states that compact mode is supported, but code is not written for it. https://github.com/hausbus/ioBroker.hausbus_de/blob/main/io-package.json#L74 .Would be cool to see it supported ...
  *   see ***@***.***#r84160575<https://github.com/hausbus/ioBroker.hausbus_de/commit/4c331b3930457a9b8d8dbb42d06c7349644d61e8#r84160575>

Thank you for checking and adjusting to the comments

Ingo

—
Reply to this email directly, view it on GitHub<https://github.com/ioBroker/ioBroker.repositories/pull/1894#issuecomment-1249265984>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHEIMDUGDGWSR3HF7ZVIKLLV6RM4LANCNFSM56FZXZXQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-09-16 12:35 UTC, Apollon77 commented
Hm ... did the creater created it would the plugin in 3.x version? OR was the creation creating it as 2.x version of the release script nd you upgraded to 3?

If it was created as 3.x this is worh an creator issue!

2022-09-18 15:11 UTC, Apollon77 commented
Pleas ejust poke when review comments are adressed

2022-09-18 15:31 UTC, hausbus commented
Wie poked man denn ?

Von: Ingo Fischer ***@***.***>
Gesendet: Sonntag, 18. September 2022 17:11
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894)


Pleas ejust poke when review comments are adressed

—
Reply to this email directly, view it on GitHub<https://github.com/ioBroker/ioBroker.repositories/pull/1894#issuecomment-1250328479>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHEIMDRAQU6YCRTGZ7KV75DV64WJ5ANCNFSM56FZXZXQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-09-18 15:39 UTC, Apollon77 commented
indem Du einfach hier kommentierst und Feedback gibst :-)

2022-09-18 15:46 UTC, hausbus commented
Ich glaube ich muss mich noch etwas an diese Arbeitsweise gewöhnen. Ich bin den github style noch nicht so gewöhnt.
Waren jetzt noch weitere Dinge offen? Die dependencies hatte ich gerade entfernt

2022-09-18 15:49 UTC, Apollon77 commented
Ich hatte in https://github.com/ioBroker/ioBroker.repositories/pull/1894#issuecomment-1249265984 alles zusammengefasst ... da alles angeschaut?

2022-09-18 15:50 UTC, hausbus commented
Yop, das sollte alles erledigt sein

2022-09-18 17:49 UTC, Apollon77 commented
ok, then here my recheck:

You removed the dependencies os/dgram. good. Please also release a new version now :-)

To jsut set compact to false in the settings was the cheapest of all solutions ... formally we require all new adapters to have compact mode support. DO you think you can adjust the code? It should not be that much:
* add code like this to the end https://github.com/Apollon77/ioBroker.nut/blob/master/nut.js#L469-L475
* move the "adapter initialization in a startAdapter method that returns the adapter instance afterwards (see https://github.com/Apollon77/ioBroker.nut/blob/master/nut.js#L25-L30) ...
Thats basically it ... and do a short testing by enabling compact mode support for the js.controller you use and enable compact mode for the adater. Would be awesome. Thank you!

2022-09-19 17:59 UTC, hausbus commented
poke :-)
I added the code for the compact mode. It seems to work. At least it still started. I don't think that I can test any further right?
Or is it possible to verify that the adapter is now running in the js-controller instance ?
New release is 1.0.17

2022-09-19 21:29 UTC, Apollon77 commented
Sure you can test compact mode and it would be cool if you do :-) See https://github.com/ioBroker/ioBroker.js-controller#start-adapter-instances-in-compact-mode ... beside CLI you can also do that via Admin

The release script increases both versions WHEN oyu use v2.x OR do a correct upgrade to 3.x of the rerlease script.This is what I wrote above! Version 3 of the release script is a major change ... Major means Breaking! see https://github.com/AlCalzone/release-script#plugins ... So you need another plugin dependency and a release script config. Then this works again.

For the Auto-Merge support you need to add a Github action Secret, see https://github.com/hausbus/ioBroker.hausbus_de/blob/main/.github/workflows/dependabot-auto-merge.yml#L22

2022-09-20 17:16 UTC, hausbus commented
I now testet compact mode. After moving the adapter to compact group 0 the admin shows mit that my adapter is no longer consuming any memory :)
I already tried to upgrate to release script 3.x like you recommended but missed adding the addon to the command line call. 

Now my build is still failing due to an invalid lock file:
npm ERR! Invalid: lock file's @alcalzone/release-script@2.2.2 does not satisfy @alcalzone/release-script@^3.5.9

Any Idea how to fix that ?

Except that you could now check version 1.0.20. Thanks!

Herm

2022-09-21 11:26 UTC, Apollon77 commented
>  npm ERR! Invalid: lock file's @alcalzone/release-script@2.2.2 does not satisfy @alcalzone/release-script@^3.5.9

Seems your package-lock run out if sync. you need to run "npm i "in the adapter dir on your dev system when updating dependencies, then package-locj is also updated

2022-09-25 15:02 UTC, hausbus commented
Ok, that seems to be fixed now. Thanks

2022-10-14 10:04 UTC, Apollon77 requested changes
Hey, so reveiw wise we are done and I would merge, but for these two topics ... please adjust or htell me what version and we can merge it!

2022-10-14 10:04 UTC, Apollon77 commented on sources-dist-stable.json
> +    "icon": "https://github.com/hausbus/ioBroker.hausbus_de/blob/main/admin/hausbusde.png",
please adjust to raw.githubusercontent.com!

2022-10-14 10:04 UTC, Apollon77 commented on sources-dist-stable.json
> +    "version": "1.0.16"
Do you want to increase version for stable before I merge?

2022-10-14 10:34 UTC, hausbus commented on sources-dist-stable.json
> +    "version": "1.0.16"
Hi Apollon,
sorry for my lack of experience but how do I get the file to raw.githubusercontent.com? If I just change the url the file cannot be found.

2022-10-14 10:36 UTC, Apollon77 commented on sources-dist-stable.json
> +    "version": "1.0.16"
https://raw.githubusercontent.com/hausbus/ioBroker.hausbus_de/main/admin/hausbusde.png should be correct ....  the structure is slightly different ... but there should be >500 comparable entries to look at *gg*

2022-10-22 18:36 UTC, hausbus commented on sources-dist-stable.json
> +    "version": "1.0.16"
How does it look now? I also updated the version to the latest release 1.1.2

2022-10-22 18:47 UTC, Apollon77 commented on sources-dist-stable.json
> +    "version": "1.0.16"
Innfact yopi set the version there which is "proofed stable, some days released already from your perspecticve and indeally also no issues reported and such"

2022-10-22 18:53 UTC, hausbus commented on sources-dist-stable.json
> +    "version": "1.0.16"
Ähm... What does that mean ?

2022-10-22 19:33 UTC, Apollon77 commented on sources-dist-stable.json
> +    "version": "1.0.16"
Ok I switch to german:
DIe Idee des "Stable" Repositories und damit der Versionsangabe ist es als Stabil bewiesene Versionen für die Allgemeinheit der User anzubieten. neue Versionen kommen nach Publish auf npm automatisch ins Beta Repo. Wenn dann eine Version dort 1-2 Wochen stabil lieff, gutes Feedback und keine Fehler vorliegen dann machst Du einen PR mit einer neuen Stabilen Version.

Also die Stable Version ist die wo Du sagst "Die ist stabil und gut für alle"

2022-10-22 19:36 UTC, hausbus commented on sources-dist-stable.json
> +    "version": "1.0.16"
Ok, verstanden. Dann erstelle ich in 2 Wochen einen neuen Pullrequest. Was passiert mit diesem hier? Wird der geschlossen ?

2022-11-16 08:32 UTC, Apollon77 commented
Welcome in the repo :-)

2022-11-16 08:34 UTC, merged

2023-03-25 20:38 UTC, hausbus commented
Hallo Ingo,
kannst du mir nochmal auf die Sprünge helfen?
Ich wollte gerade unseren Adapter aktualisieren und bekomme nun folgendes:

npm ERR! notsup Unsupported engine for ***@***.***: wanted: {"node":">=14.18.0 < 15 || >= 16.4.0"} (current: {"node":"12.22.12","npm":"6.14.16"})

Muss ich irgendwo neues Dependencies eintragen ?

Danke!
Herm

Von: Ingo Fischer ***@***.***>
Gesendet: Mittwoch, 16. November 2022 09:35
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894)


Merged #1894<https://github.com/ioBroker/ioBroker.repositories/pull/1894> into master.

—
Reply to this email directly, view it on GitHub<https://github.com/ioBroker/ioBroker.repositories/pull/1894#event-7821323393>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHEIMDTJ6TJ2CML5R7PZQ23WISMBTANCNFSM56FZXZXQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-03-25 22:15 UTC, mcm1957 commented
Dieser PR ist wohl nicht der geeignete Platz für Nachfragen :-)
Bitte Telegram oder Forum benutzen.
Das Problem scheint zu sein, dass auf dem System node12 läuft. Dieses wird nicht mehr unterstützt.

2023-03-26 09:35 UTC, Apollon77 commented
@hausbus Wo beskommst du das? Bei den tests? Dannbitte nodejs 12 aus den test rausnehmen! Siehe https://forum.iobroker.net/topic/63825/controller-v5-kein-support-von-node-js-12

2023-03-26 11:06 UTC, hausbus commented
Vielen Dank, hat geklappt.
Nochmal eine Frage. Ich habe gerade eine neue Version released. Wie lange dauert es, bis die Version im Betarepository angezeigt wird?
Oder passiert das nicht automatisch, wenn ich die Version von 1.1.5 auf 1.2.1 erhöht habe ?

Danke!
Herm


Von: Ingo Fischer ***@***.***>
Gesendet: Sonntag, 26. März 2023 11:36
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894)


@hausbus<https://github.com/hausbus> Wo beskommst du das? Bei den tests? Dannbitte nodejs 12 aus den test rausnehmen! Siehe https://forum.iobroker.net/topic/63825/controller-v5-kein-support-von-node-js-12

—
Reply to this email directly, view it on GitHub<https://github.com/ioBroker/ioBroker.repositories/pull/1894#issuecomment-1484044324>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHEIMDWDDPLPIWNJS6OT6J3W6ALXZANCNFSM56FZXZXQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-03-26 12:28 UTC, mcm1957 commented
Latest wurd typich 2x Rag ca 14:00 und 2:00 aktualisiert. Latest update sillte immer automatisch erfolgenMcM
-------- Ursprüngliche Nachricht --------Von: Hermann Hoeschen ***@***.***> Datum: 26.03.23  13:07  (GMT+01:00) An: "ioBroker/ioBroker.repositories" ***@***.***> Cc: "Martin M." ***@***.***>, Comment ***@***.***> Betreff: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894) 
Vielen Dank, hat geklappt.

Nochmal eine Frage. Ich habe gerade eine neue Version released. Wie lange dauert es, bis die Version im Betarepository angezeigt wird?

Oder passiert das nicht automatisch, wenn ich die Version von 1.1.5 auf 1.2.1 erhöht habe ?



Danke!

Herm





Von: Ingo Fischer ***@***.***>

Gesendet: Sonntag, 26. März 2023 11:36

An: ioBroker/ioBroker.repositories ***@***.***>

Cc: Hermann Hoeschen ***@***.***>; Mention ***@***.***>

Betreff: Re: [ioBroker/ioBroker.repositories] Added haus-bus.de adapter (PR #1894)





@hausbus<https://github.com/hausbus> Wo beskommst du das? Bei den tests? Dannbitte nodejs 12 aus den test rausnehmen! Siehe https://forum.iobroker.net/topic/63825/controller-v5-kein-support-von-node-js-12



—

Reply to this email directly, view it on GitHub<https://github.com/ioBroker/ioBroker.repositories/pull/1894#issuecomment-1484044324>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHEIMDWDDPLPIWNJS6OT6J3W6ALXZANCNFSM56FZXZXQ>.

You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>